name: PI-Build

on:
  push:
    branches:
      - master
      - feature/*
      - bugfixing/*
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build (Gradle)
        run: ./gradlew build stage