name: PI-Release

on:
    workflow_dispatch:
        inputs:
            releaseType:
                description: 'Release type (major, minor, patch)'
                type: choice
                options:
                    - 'major'
                    - 'minor'
                    - 'patch'
                required: true
                default: 'patch'

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Set up Git user
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"

            - name: Prepare release
              run: ./gradlew release -PreleaseType=${{ github.event.inputs.releaseType }}
