name: PI-Release

on:
    workflow_dispatch:
        inputs:
            releaseType:
                description: 'Release type (major, minor, patch)'
                required: true
                default: 'patch'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Prepare release
              run: ./gradlew release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${{ github.event.inputs.releaseType }}
